### PR TITLE
Add email provider

### PR DESCRIPTION
**Pull request by calvera**
allow using email instead of username

### CODE REVIEW

**Comment by aequasi** [comment]
I'm a little confused. This doesn't seem to do anything.

**Comment by calvera** [comment]
see this https://symfony.com/doc/current/bundles/FOSUserBundle/logging_by_username_or_email.html

**Comment by aequasi** [comment]
Yes, but this provider ONLY fetches by ID. You just copied the user provider, and changed the name of the class. Nothing is done with an email here.

**Comment by calvera** [comment]
really? :)

https://github.com/calvera/api-key-bundle/blob/email-provider/src/Uecode/Bundle/ApiKeyBundle/Security/Authentication/Provider/EmailUserProvider.php#L4

**Comment by aequasi** [comment]
Ill merge it, but im not really sure how this is being used. Its fetching by API key, not by username/email.

**Pull request merged**
